services:
  api:
    build: .
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=postgresql://student_admin:vibecode2026pg@172.17.0.1:5433/db_olenap
      - TEACHER_PASSWORD=math2024
      - PORT=3000
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
